# Generated by Django 4.2.29 on 2026-03-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_comment_remove_lead_interactions_lead_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='connections',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='followup1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='followup1_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('linkedin', 'LinkedIn')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='followup2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='followup2_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('linkedin', 'LinkedIn')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_enriched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='outreach_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='outreach_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('linkedin', 'LinkedIn')], max_length=10, null=True),
        ),
    ]
