# Generated by Django 4.2.29 on 2026-03-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_company_website_lead_connections_lead_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='is_enriched',
        ),
    ]
