# Generated by Django 4.2.29 on 2026-03-05 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_is_enriched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='followup1_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='followup1_method',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='followup2_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='followup2_method',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='outreach_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='outreach_method',
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('email', 'Email'), ('linkedin', 'LinkedIn')], max_length=10)),
                ('status', models.CharField(choices=[('no_reply', 'No Reply'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], default='no_reply', max_length=15)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_records', to='leads.lead')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
