# Generated by Django 4.2.29 on 2026-03-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_lead_followup1_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('no_reply', 'No Reply'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], default='pending', max_length=15),
        ),
    ]
