# Generated by Django 4.2.29 on 2026-03-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_outreach_audio_file_outreach_script_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_me',
            field=models.TextField(blank=True, default=''),
        ),
    ]
