# Generated by Django 4.2.29 on 2026-03-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_sitesettings_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company_website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='linkedin_profile',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
