# Generated by Django 4.2.29 on 2026-03-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_widen_url_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
