# Generated by Django 4.2.29 on 2026-03-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='audio_file',
            field=models.FileField(blank=True, default='', upload_to='voice_notes/'),
        ),
        migrations.AddField(
            model_name='outreach',
            name='script_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='method',
            field=models.CharField(choices=[('email', 'Email'), ('linkedin', 'LinkedIn'), ('voice', 'Voice')], max_length=10),
        ),
    ]
